//   usegetDescription
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { BASE_URL } from "../../config/Config";
import axios from "axios";

const getDescription = async (value) => {
  const Post = `${BASE_URL}api/jobs/job-suggestions/?query=${value}&field=job`;
  const res = await axios.get(Post);
  return res;
};

export const useAutoGenerateDecsciption = (val) => {
  const { data, isLoading, isError, status } = useQuery({
    queryKey: ["suggestion", val],
    queryFn: () => getDescription(val),
    enabled: val.length > 2,
  });

  return { data, isLoading };
};
